kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.122.0.0/16"
  serviceSubnet: "10.46.0.0/12"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: .
    containerPath: /etc/kubernetes/audit
- role: worker
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      profiling: "false"
      audit-log-path: "/var/log/kubernetes/audit/audit.log"
      audit-log-maxage: "30"
      audit-log-maxbackup: "10"
      audit-log-maxsize: "100"
      audit-policy-file: "/etc/kubernetes/audit/audit-policy.yaml"
      kubelet-certificate-authority: "/etc/kubernetes/pki/ca.crt"
    extraVolumes:
      - name: audit-log
        hostPath: /var/log/kubernetes/audit
        mountPath: /var/log/kubernetes/audit
        readOnly: false
      - name: audit-policy
        hostPath: /etc/kubernetes/audit
        mountPath: /etc/kubernetes/audit
        readOnly: true
  controllerManager:
    extraArgs:
      profiling: "false"
  scheduler:
    extraArgs:
      profiling: "false"
