kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.122.0.0/16"
  serviceSubnet: "10.46.0.0/12"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /var/log/kubernetes/audit
    containerPath: /var/log/kubernetes/audit
    readOnly: false
- role: worker
kubeadmConfigPatches:
- |
  kind: InitConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      anonymous-auth: "false"
- |
  kind: ClusterConfiguration
  apiServer:
    timeoutForControlPlane: 10s
    extraArgs:
      profiling: "false"
      audit-log-path: "/var/log/kubernetes/audit/audit.log"
      audit-log-maxage: "30"
      audit-log-maxbackup: "10"
      audit-log-maxsize: "100"
      # kubelet-certificate-authority: "/etc/kubernetes/pki/kubelet-ca.crt"
    extraVolumes:
    - name: audit-logs
      hostPath: /var/log/kubernetes/audit
      mountPath: /var/log/kubernetes/audit
      readOnly: false
  controllerManager:
    extraArgs:
      profiling: "false"
  scheduler:
    extraArgs:
      profiling: "false"
