kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.122.0.0/16"
  serviceSubnet: "10.46.0.0/12"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./rules
    containerPath: /etc/falco/rules.d/
    readOnly: true
- role: worker
  extraMounts:
  - hostPath: ./rules
    containerPath: /etc/falco/rules.d/
    readOnly: true
  labels:
    worker-node: "true"
