apiVersion: v1
kind: Pod
metadata:
  name: restricted-network-pod
spec:
  containers:
  - name: restricted-network-access
    image: nicolaka/netshoot
    command: ["sh", "-c", "echo 'Waiting' && sleep 1h"]
    securityContext:
      appArmorProfile:
        type: Localhost
        localhostProfile: k8s-network-restricted
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "16Mi"
        cpu: "50m"
  - name: unrestricted-network-access
    image: nicolaka/netshoot
    command: ["sh", "-c", "echo 'Waiting' && sleep 1h"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "16Mi"
        cpu: "50m"